Use _DEFAULT_SOURCE, not deprecated _BSD_SOURCE
This fixes the compile error introduced in commit f152bf6.

/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]